package br.com.ieptbto.cra.enumeration;

public enum CraServices {

							ARQUIVOS_PENDENTES_CARTORIO,

							ENVIO_ARQUIVO_REMESSA,
							DOWNLOAD_ARQUIVO_CONFIRMACAO,
							DOWNLOAD_ARQUIVO_RETORNO,
							ENVIO_ARQUIVO_DESISTENCIA_PROTESTO,
							ENVIO_ARQUIVO_CANCELAMENTO_PROTESTO,
							ENVIO_ARQUIVO_AUTORIZACAO_CANCELAMENTO,

							DOWNLOAD_ARQUIVO_REMESSA,
							ENVIO_ARQUIVO_CONFIRMACAO,
							ENVIO_ARQUIVO_RETORNO,
							DOWNLOAD_ARQUIVO_DESISTENCIA_CANCELAMENTO,
							CONFIRMAR_RECEBIMENTO_DESISTENCIA_CANCELAMENTO,

							DOWNLOAD_ARQUIVO_CENTRAL_NACIONAL_PROTESTO,
							ENVIO_ARQUIVO_CENTRAL_NACIONAL_PROTESTO,
							ENVIO_CNP_5_ANOS,
							CONSULTA_PROTESTO;
}
